export interface NoticeVO extends BaseEntity {
  noticeId: number;
  noticeTitle: string;
  noticeType: string;
  noticeContent: string;
  status: string;
  remark: string;
  createByName: string;
  businessCategory?: string;
  pushRange?: string;
  pushStatus?: string;
  audienceType?: string;
  targetAllScope?: string;
  targetUserSegment?: string;
  targetDeptIds?: string | Array<string | number>;
  targetUserIds?: string | Array<string | number>;
  targetRoleIds?: string | Array<string | number>;
  targetTags?: string | string[];
  readRate?: number | string;
  unreadCount?: number | string;
  scheduleTime?: string;
  validEndTime?: string;
  publishTime?: string;
  forcePopup?: string;
  isTop?: string;
  isRed?: string;
  excludeUsers?: string | Array<string | number>;
  periodCycle?: string;
  weekDay?: string;
  sendTime?: string;
  periodStartTime?: string;
  periodEndTime?: string;
  periodStatus?: string;
  dataAudience?: string;
  segmentTag?: string;
  dataReportType?: string;
  reportTemplate?: string;
  autoPdf?: string;
  unreadLayerSummary?: string;
  targetUserCount?: number | string;
  readCount?: number | string;
  highIntentReadCount?: number | string;
  sleepUnreadCount?: number | string;
}

export interface NoticeQuery extends PageQuery {
  noticeTitle: string;
  createByName: string;
  status: string;
  noticeType: string;
  businessCategory?: string;
  pushStatus?: string;
  audienceType?: string;
  periodCycle?: string;
  dataAudience?: string;
  segmentTag?: string;
  periodStatus?: string;
  keyword?: string;
  isTop?: string;
  isRed?: string;
}

export interface NoticeForm {
  noticeId: number | string | undefined;
  noticeTitle: string;
  noticeType: string;
  noticeContent: string;
  status: string;
  remark: string;
  createByName: string;
  businessCategory?: string;
  pushRange?: string;
  pushStatus?: string;
  audienceType?: string;
  targetAllScope?: string;
  targetUserSegment?: string;
  targetDeptIds?: string | Array<string | number>;
  targetUserIds?: string | Array<string | number>;
  targetRoleIds?: string | Array<string | number>;
  targetTags?: string | string[];
  scheduleTime?: string;
  validEndTime?: string;
  publishTime?: string;
  forcePopup?: string;
  forceRead?: string;
  channelInSite?: string;
  channelApp?: string;
  channelSms?: string;
  excludeUsers?: string | Array<string | number>;
  periodCycle?: string;
  weekDay?: string;
  sendTime?: string;
  periodStartTime?: string;
  periodEndTime?: string;
  periodStatus?: string;
  dataAudience?: string;
  segmentTag?: string;
  dataReportType?: string;
  reportTemplate?: string;
  autoPdf?: string;
}
